//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GitHub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class estudiantesSet
    {
        public int Idestudiantes { get; set; }
        public string materia { get; set; }
        public string nombre { get; set; }
    }
}
