//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GitHub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class grupo2
    {
        public int Id { get; set; }
        public string Nombre_del_estudiante { get; set; }
        public string Materias { get; set; }
        public string Cuatrimestres_cursados { get; set; }
    }
}
