//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GitHub.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GHBbdEntities : DbContext
    {
        public GHBbdEntities()
            : base("name=GHBbdEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<eventosSet> eventosSet { get; set; }
        public virtual DbSet<Table> Table { get; set; }
        public virtual DbSet<grupo1> grupo1 { get; set; }
        public virtual DbSet<grupo2> grupo2 { get; set; }
    }
}
